version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./sql/create.sql:/docker-entrypoint-initdb.d/create.sql"
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
